### ISSUE TITLE
Multiline Ressource strings

### ISSUE THREAD

**Issue by khkroenig** [TagBites/LSACreator-Docs#1]
In VS Ressource-Editor I can add a new line using Shift-Enter. Using \r\n ist not working. 
In LSA-Creator Shift-Enter ist not working, thus Multiline strings seems not to be possible.
Any ideas?
Thanks,
Karl

**Comment by tomaszmalik** [comment]
There is an icon in top right corner "Show text editor". If you turn it on, you will see text editor in the bottom, which works with both Enter and Shift+Enter. The editor is enabled for active cell in grid above. Is that what you need?

![Example](https://user-images.githubusercontent.com/22030521/63546129-544a5780-c529-11e9-8cb6-6d0284ea9fc1.png)

**Comment by khkroenig** [comment]
Oh, good morning!
Yes, thats it. Shame on me, I haven't seen that.
Thank you and
Best regards,

Mit freundlichen Grüßen,
Karl Heinz Krönig
Khkroenig@gmail.com

Tomasz Malik <notifications@github.com> schrieb am Do., 22. Aug. 2019,
22:16:
